apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: three-tire
  name: mongodb
spec:
replicas: 1
selector:
  matchLabels:
    app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mon
        images: mongodb:4.4.6
        command:
        - "numactl"
        - "--interlive=all"
        - "mongod"
        - "--wiredTigerCacheSizeGB"
        - "0.1"
        - "--bind-ip"
        - "0.0.0.0"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-sec
              key: username
        - name: MONGODB_INITDB_ROOT_PASWORD
          valueFrom:
            secretKeyRef:
              name: mongo-sec
              key: password
        valumeMounts:
        - name: mongo-volume
          mountPath: /data/db
      valumes:
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: mongo-volume-claim
