vpc-name = "jenkins-vpc"
subnet-name = "jenkins-subnet"
igw-name = "jenkins-igw"
sg-name = "jenkins-sg"
rt-name = "jenkins-rt"
key-name = "ins-ins"
iam-role = "jenkins-iam-role"
instance-name = "jenkins-server-instane"